def do_help():
    print("Available commands: \n \n")
    print("--help \n Prints this message with all commands and their arguments")
    print("--brightness \n -input=<path>    Path to the input image \n -output=<path>   Path to save the image \n -const=<value>    Brightness adjustment constant (integer between -255 and 255) \n")
    print("--contrast \n -input=<path>    Path to the input image \n -output=<path>   Path to save the image \n -factor=<value>   Contrast adjustment factor (float, e.g., 1.2 for increase, 0.8 for decrease) \n")
    print("--negative \n -input=<path>    Path to the input image \n -output=<path>   Path to save the image \n")
    print("--hflip \n -input=<path>    Path to the input image \n -output=<path>   Path to save the image \n")
    print("--vflip \n -input=<path>    Path to the input image \n -output=<path>   Path to save the image \n")
    print("--dflip \n -input=<path>    Path to the input image \n -output=<path>   Path to save the image \n")
    print("--adaptive \n -input=<path>    Path to the input image \n -output=<path>   Path to save the image \n -sMin=<value default 3> minimum window size \n -sMax=<value default 9> maximum window size")
    print("--min \n -input=<path>    Path to the input image \n -output=<path>   Path to save the image \n -window=<value default 3> size of the filtering window")
    print("--max \n -input=<path>    Path to the input image \n -output=<path>   Path to save the image \n -window=<value default 3> size of the filtering window")
    print("--mse \n -original=<path>    Path to the original image with no noise \n -other=<path>   Path to the image with noise/denoised image \n")
    print("--pmse \n -original=<path>    Path to the original image with no noise \n -other=<path>   Path to the image with noise/denoised image \n")
    print("--snr \n -original=<path>    Path to the original image with no noise \n -other=<path>   Path to the image with noise/denoised image \n")
    print("--psnr \n -original=<path>    Path to the original image with no noise \n -other=<path>   Path to the image with noise/denoised image \n")
    print("--md \n -input=<path>    Path to the original image with no noise \n -other=<path>   Path to the image with noise/denoised image \n")

